name: "attention_rnn"
task_name: "svhn_digit"
shrink_dataset_by: 1
n_epochs: 100
batch_size: 100
hidden_dim: 256
n_patches: 8
patch_shape: [8, 8]
patch_transform_spec:
#    cnn:
#        - border_mode: full
#          filter_size: [4, 4]
#          num_filters: 32
#        - border_mode: full
#          filter_size: [4, 4]
#          num_filters: 32
     mlp: [128]
area_dim: 64
learning_rate: 0.0001
batched_window: True
cutoff: 3
plot_url: http://bart2:5006/
location_std: 0.1
scale_std: 0.01
