name: "attention_rnn"
task_name: "svhn_digit"
shrink_dataset_by: 1
n_epochs: 100
batch_size: 100
hidden_dim: 256
n_patches: 8
patch_shape: [8, 8]
area_dim: 128
# whether patch should go through a convnet or an fcnet
convolutional: False
learning_rate: 1e-3
batched_window: True
cutoff: 3
plot_url: http://bart2:5006/
